// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdePR2ulZ6GhLPIwRYMUffa5Rj32Zyq_Y',
    appId: '1:601408095464:android:756e1aefc0afbc5fcaf55d',
    messagingSenderId: '601408095464',
    projectId: 'chess-defense-98af5',
    databaseURL: 'https://chess-defense-98af5-default-rtdb.firebaseio.com',
    storageBucket: 'chess-defense-98af5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKu5023A6CBEJw8d_smHrMNTLc3hyd98w',
    appId: '1:601408095464:ios:a0150d83b8c0225dcaf55d',
    messagingSenderId: '601408095464',
    projectId: 'chess-defense-98af5',
    databaseURL: 'https://chess-defense-98af5-default-rtdb.firebaseio.com',
    storageBucket: 'chess-defense-98af5.firebasestorage.app',
    iosBundleId: 'com.jinpyok.chessDefense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKu5023A6CBEJw8d_smHrMNTLc3hyd98w',
    appId: '1:601408095464:ios:a0150d83b8c0225dcaf55d',
    messagingSenderId: '601408095464',
    projectId: 'chess-defense-98af5',
    databaseURL: 'https://chess-defense-98af5-default-rtdb.firebaseio.com',
    storageBucket: 'chess-defense-98af5.firebasestorage.app',
    iosBundleId: 'com.jinpyok.chessDefense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXxo31fmAJLa6NASNIqElnLMUGPrcaJiA',
    appId: '1:601408095464:web:9d3c18e6b81aaea5caf55d',
    messagingSenderId: '601408095464',
    projectId: 'chess-defense-98af5',
    authDomain: 'chess-defense-98af5.firebaseapp.com',
    databaseURL: 'https://chess-defense-98af5-default-rtdb.firebaseio.com',
    storageBucket: 'chess-defense-98af5.firebasestorage.app',
  );
}
